sudo: required
language: generic 

services:
  - docker

#before_install:
#  - docker build -t patbowe/react-test -f ./client/Dockerfile.dev ./client

#script: 
#  - docker run patbowe/react-test npm test -- --coverage
 
after_success:
  - docker build ./client -t patbowe/multi-client -f ./client/Dockerfile
  - docker build -t patbowe/multi-nginx ./nginx
  - docker build -t patbowe/multi-server ./server
  - docker build -t patbowe/multi-worker ./worker
  - docker images
  - docker tag patbowe/multi-worker patbowe/proutman:latest
  - docker images
  # Log in to the docker CLI
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  # Take those images and push them to docker hub repos
  - docker push patbowe/multi-client:latest
  - docker push docker.io/patbowe/multi-nginx:latest
  - docker push docker.io/patbowe/multi-server:latest
  - docker push docker.io/patbowe/proutman:latest
